-- ============================================
-- 해충 방제 프로젝트 - Oracle Database Schema
-- ============================================

-- 기존 테이블 및 시퀀스 삭제
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE INQUIRIES CASCADE CONSTRAINTS;
DROP TABLE ADMINS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_REVIEW_ID;
DROP SEQUENCE SEQ_INQUIRY_ID;
DROP SEQUENCE SEQ_ADMIN_ID;

-- 1. 관리자 테이블
CREATE TABLE ADMINS (
    ADMIN_ID        NUMBER          PRIMARY KEY,
    USERNAME        VARCHAR2(50)    NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(255)   NOT NULL,
    ADMIN_NAME      VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100),
    CREATED_AT      DATE            DEFAULT SYSDATE
);

-- 관리자 ID 시퀀스
CREATE SEQUENCE SEQ_ADMIN_ID START WITH 1 INCREMENT BY 1;

-- 2. 문의 테이블
CREATE TABLE INQUIRIES (
    INQUIRY_ID      NUMBER          PRIMARY KEY,
    NAME            VARCHAR2(50)    NOT NULL,
    COMPANY_NAME    VARCHAR2(100),
    PHONE           VARCHAR2(20)    NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL,
    TITLE           VARCHAR2(200)   NOT NULL,
    CONTENT         CLOB            NOT NULL,
    ATTACHMENT      VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'pending' CHECK (STATUS IN ('pending', 'in_progress', 'completed')),
    ADMIN_NOTE      CLOB,
    CREATED_AT      DATE            DEFAULT SYSDATE,
    RESPONDED_AT    DATE
);

-- 문의 ID 시퀀스
CREATE SEQUENCE SEQ_INQUIRY_ID START WITH 1 INCREMENT BY 1;

-- 3. 서비스 후기 테이블
CREATE TABLE REVIEWS (
    REVIEW_ID       NUMBER          PRIMARY KEY,
    ADMIN_ID        NUMBER          NOT NULL REFERENCES ADMINS(ADMIN_ID),
    TITLE           VARCHAR2(200)   NOT NULL,
    SERVICE_DATE    DATE            NOT NULL,
    CONTENT         CLOB            NOT NULL,
    IMAGE           VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'published' CHECK (STATUS IN ('draft', 'published')),
    CREATED_AT      DATE            DEFAULT SYSDATE,
    UPDATED_AT      DATE
);

-- 서비스 후기 ID 시퀀스
CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1;

COMMIT;
